---
- name: Setup apt repositories
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"

- name: Apt update
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes
