---
- name: Setup apt repositories
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"
  when: ansible_distribution == 'MacOSX'
  become: true

- name: Apt update
  apt:
    update_cache: true
  become: true

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true
  become: true

# TODO: Pull this out into a git-machete role
- name: Install git-machete auto completion
  get_url:
    url: https://raw.githubusercontent.com/VirtusLab/git-machete/master/completion/git-machete.completion.bash
    dest: /etc/bash_completion.d/git-machete 
  become: true
