
---
- name: Setup brew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Install brew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
